# 站点设置Site settings
title: 小王的个人博客 # 网站主标题
SEOTitle: 个人博客 - 让理解更轻松
header-img: img/post-bg-desk.jpg # 显示在首页的背景图片
email: 1548390588@qq.com
description: "本项目为个人公共博客，所有文章均为原创，转载请注明出处。" # 主标题下的简介
keyword: "软件工程，计算机图形学, 深度学习, "
url: "https://123wangju123.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/123wangju123/123wangju123.github.io.git" # you code repository

# 侧边栏设置（Sidebar settings）
sidebar: true                           # 是否开启左边栏.
sidebar-about-description: "我每天都很幸福!"  
sidebar-avatar: /img/about-someone.jpg      # 个人头像


# 社交帐号设置
# SNS settings 
showFooterSNS: False # 是否展示网站底部的社交账号信息
RSS: False
# weibo_username:     qiubaiying
# zhihu_username:     qiubaiying
github_username:    MagicDeveloperDRL
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
# twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: d18b343dd9c7ca49518a                            #生成的clientID
  clientSecret: 539e88b8a7feffaddbb553b9c421dfefcbc6eced    #生成的clientSecret
  repo: klovien.github.io    #仓库名称
  owner: klovien    #github用户名
  admin: klovien
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# 特征标签（Featured Tags）
featured-tags: true                     # 是否使用特征标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# 友情链接
friends: [
    {
        title: "CSDN博客",
        href: "https://blog.csdn.net/qq_41959920"
    },{
        title: "星球语互动社区",
        href: "https://tieba.baidu.com/f?kw=%E6%A0%BC%E7%BD%97%E6%AF%94%E8%A8%80&fr=home"
    },
]
